version: '3'
services:
  db:
    container_name: library_db
    image: mariadb:10.6.12
    ports:
      - "3303:3303"
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./diff_db.sql:/docker-entrypoint-initdb.d/diff_db.sql
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: library
      MYSQL_TCP_PORT: 3303
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--user=root", "--password=root" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: unless-stopped